### ISSUE TITLE
Doesn't even attempt to catch the pokemon?

### ISSUE THREAD

**Issue by MarcusDDS1609** [K1mpl0s/pcord-catcher#1]
The spammer works fine, but it doesn't attempt to catch any pokemon at all. It's like the embed isn't even detected?

**Comment by K1mpl0s** [comment]
Hello,

I have decided to rewrite the entire script to make it faster & be able to automatically detect the pokecord prefix. Soon will also provide an option to auto-detect groups instead of entering them into config.
The finish product can be seen here:
https://github.com/K1mpl0s/pokecord-autocatcher/tree/master
Please note this version does not use google & does not have the spam command but spam will be added there shortly.

Best regards, k1mpl0s.
